
name: Commit Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get commit details
        id: commit_details
        run: |
          echo "author=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
          echo "message=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV
          echo "url=$(git log -1 --pretty=format:'%H')" >> $GITHUB_ENV

      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: C07TXCTCEMD
          payload: |
            {
              "channel": "C07TXCTCEMD",
              "text": "¡Nuevo commit en la rama *main*! 🎉",
              "attachments": [
                {
                  "color": "#36a64f",
                  "pretext": "Detalles del commit:",
                  "fields": [
                    {
                      "title": "Autor",
                      "value": "${{ env.author }}",
                      "short": true
                    },
                    {
                      "title": "Mensaje",
                      "value": "${{ env.message }}",
                      "short": true
                    },
                    {
                      "title": "Commit URL",
                      "value": "<https://github.com/${{ github.repository }}/commit/${{ env.url }}|Ver commit>",
                      "short": true
                    }
                  ],
                  "footer": "GitHub Actions",
                  "footer_icon": "https://platform.slack-edge.com/img/default_application_icon.png",
                  "ts": "${{ github.event.head_commit.timestamp }}"
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
